config/routes.rb
Rails.application.routes.draw do
  get 'starship/index'

  get 'planet/index'

  get 'character/index'

  get 'pelicula/index'
  get    '/search',     to: 'welcome#search'
  root 'welcome#index'
  get '/welcome', to: 'welcome#index' 
  get '/pelicula', to: 'pelicula#index'
  get '/character', to: 'character#index'
  get '/planet', to: 'planet#index'
  get '/starship', to: 'starship#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController
  def index
    self.params = params.permit!
    idp = params["content"]
    response1 =  HTTParty.post("https://swapi-graphql-integracion-t3.herokuapp.com/",
               headers: {'content-type': 'application/json'},
               body:{"query": "query{person(id: \"#{idp}\"){name,birthYear,eyeColor,gender,hairColor,height,mass,skinColor,homeworld{name, id},
                       filmConnection{films{title,episodeID, id}},
                       starshipConnection{starships{name,id}},
                       }}"}.to_json)
    @response = JSON.parse(response1.body)
    @informacion = @response["data"]["person"]
  end
end

app/controllers/pelicula_controller.rb
require "rubygems"
require "httparty"

class PeliculaController < ApplicationController
  include HTTParty
  def index
    self.params = params.permit!
    @urls =  params[:informacion]
    idp = @urls["id"]
    response1 =  HTTParty.post("https://swapi-graphql-integracion-t3.herokuapp.com/",
               headers: {'content-type': 'application/json'},
               body:{"query": "query{film(id: \"#{idp}\"){title,releaseDate,episodeID,openingCrawl,director,producers,
                       characterConnection{characters{name,id}},
                       planetConnection{planets{name,id}},
                       starshipConnection{starships{name,id}},
                       }}"}.to_json)
    @response = JSON.parse(response1.body)
	@urls = @response["data"]["film"]
	@title = @urls["title"]
	@episode = @urls["episodeID"]
	@description = @urls["openingCrawl"]
	@director = @urls["director"]
	@producer = @urls["producers"]
	@año = @urls["releaseDate"]
    @characters = @urls["characterConnection"]["characters"]
    @planets = @urls["planetConnection"]["planets"]
    @starships = @urls["starshipConnection"]["starships"]
  end
end

app/controllers/planet_controller.rb
class PlanetController < ApplicationController
  def index
    self.params = params.permit!
    idp = params["content"]
    response1 =  HTTParty.post("https://swapi-graphql-integracion-t3.herokuapp.com/",
               headers: {'content-type': 'application/json'},
               body:{"query": "query{planet(id: \"#{idp}\"){name,diameter,rotationPeriod, orbitalPeriod, gravity, population, climates
               ,terrains,surfaceWater,
               filmConnection{films{title,episodeID,id}},
               residentConnection{residents{name,id}},
                       }}"}.to_json)
    @response = JSON.parse(response1.body)
    @informacion = @response["data"]["planet"]
  end
end

app/controllers/starship_controller.rb
class StarshipController < ApplicationController

  def index
    self.params = params.permit!
    idp = params["content"]
    response1 =  HTTParty.post("https://swapi-graphql-integracion-t3.herokuapp.com/",
               headers: {'content-type': 'application/json'},
               body:{"query": "query{starship(id: \"#{idp}\"){name,model,starshipClass,manufacturers,costInCredits
               ,length,crew,passengers,maxAtmospheringSpeed, hyperdriveRating,MGLT, cargoCapacity, consumables,
                       filmConnection{films{title,episodeID,id}},
                       pilotConnection{pilots{name,id}},
                       }}"}.to_json)
    @response = JSON.parse(response1.body)
    @informacion = @response["data"]["starship"]
  end

end

app/controllers/welcome_controller.rb
require "rubygems"
require "httparty"
class WelcomeController < ApplicationController
  include HTTParty
  def index
	response1 =  HTTParty.post("https://swapi-graphql-integracion-t3.herokuapp.com/",
               headers: {'content-type': 'application/json'},
               body:{"query": "query{allFilms
						               	{edges
						               		{node
						               			{title,releaseDate,episodeID,director,producers,id}}}}"}.to_json)
	@response = JSON.parse(response1.body)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/pelicula_helper.rb
module PeliculaHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/starship_helper.rb
module StarshipHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/character/index.html.erb
<h1>STAR WAR CHARACTER</h1>

<table>
    <thead>
       <tr>
        <th>Name: </th>
        <th><%= @informacion["name"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Birth year: </th>
       	<th><%= @informacion["birthYear"] %></th>
 		

       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
       	<th>Eye color: </th>
       	<th><%= @informacion["eyeColor"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Gender: </th>
       	<th><%= @informacion["gender"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Hair color: </th>
       	<th><%= @informacion["hairColor"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Height: </th>
       	<th><%= @informacion["height"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Mass: </th>
       	<th><%= @informacion["mass"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Name: </th>
       	<th><%= @informacion["name"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Skin color: </th>
       	<th><%= @informacion["skinColor"] %></th>
       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
        <th>Homeworld: </th>
        <th><%= link_to @informacion["homeworld"]["name"], planet_path(:content=> @informacion["homeworld"]["id"] ) %></th>
       </tr>
    </thead>
</table>



<table>
    <thead>
       <tr>
       	<th>Films: </th>
       </tr>
    </thead>
    <tbody>
		<%  @informacion["filmConnection"]["films"].each do |film| %>
       	<td> </td>
       	<td><%= link_to film["title"], pelicula_path(:informacion=> film ), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>


<table>
    <thead>
       <tr>
       	<th>Starships: </th>
       </tr>
    </thead>
    <tbody>
		<%  @informacion["starshipConnection"]["starships"].each do |film| %>
       	<td> </td>
       	<td><%= link_to film["name"], starship_path(:content=> film["id"]), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<nav>
        <td><%= link_to "STARWARS", welcome_path, class: "btn btn-primary" %></td>

</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/pelicula/index.html.erb
<h1>STAR WARS PELÍCULA</h1>
	



<table>
    <thead>
       <tr>
       	<th>Título: </th>
       	<th><%= @title %></th>
 		

       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Episodio: </th>
       	<th><%= @episode %></th>
  

       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>	
       	<th>Descripción(openingCrawl): </th>
        <th colspan=10> </th>
       </tr>
    </thead>
    <tbody>
    <th colspan=10> </th>
    <th><%= @description %></th>
  </tbody>
</table>
<table>
    <thead>
       <tr>
       	<th>Director(es): </th>
       	<th><%= @director%></th>


       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>
       	<th>Productor(es): </th>
       	<th><%= @producer%></th>

       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>
       	<th>Año(release date): </th>
       	<th><%= @año %></th>


       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
        <th>Characters: </th>
        <th>  </th>
       </tr>
    </thead>
    <tbody>
    <%  @characters.each do |character| %>
        <td> </td>
        <td><%= link_to character["name"], character_path(:content=> character["id"] ), class: "btn btn-primary" %></td>
       </tr>
         <% end %>
    </tbody>
</table>

<table>
    <thead>
       <tr>
        <th>Planetas: </th>
       </tr>
    </thead>
    <tbody>
    <%  @planets.each do |planet| %>
        <td> </td>
        <td><%= link_to planet["name"], planet_path(:content=> planet["id"]), class: "btn btn-primary" %></td>
       </tr>
         <% end %>
    </tbody>
</table>
<table>
    <thead>
       <tr>
        <th>Starships: </th>
       </tr>
    </thead>
    <tbody>
    <%  @starships.each do |starship| %>
        <td> </td>
        <td><%= link_to starship["name"], starship_path(:content=> starship["id"] ), class: "btn btn-primary" %></td>
       </tr>
         <% end %>
    </tbody>
</table>

app/views/planet/index.html.erb
<h1>STAR WARS PLANET</h1>

<table>
    <thead>
       <tr>
       	<th>Name: </th>
 		   <th><%= @informacion["name"] %></th>

       </tr>
    </thead>
</table>





<table>
    <thead>
       <tr>
       	<th>Diameter: </th>
       	<th><%= @informacion["diameter"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Rotation period: </th>
       	<th><%= @informacion["rotationPeriod"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Orbital period: </th>
       	<th><%= @informacion["orbitalPeriod"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Gravity: </th>
       	<th><%= @informacion["gravity"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Climates: </th>
       	<th><%= @informacion["climates"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Population: </th>
       	<th><%= @informacion["population"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Terrains: </th>
       	<th><%= @informacion["terrains"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Surface Water: </th>
       	<th><%= @informacion["surfaceWater"] %></th>
       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
       	<th>Films: </th>
       </tr>
    </thead>
    <tbody>
		<%  @informacion["filmConnection"]["films"].each do |film| %>
       	<td> </td>
       	<td><%= link_to film["title"], pelicula_path(:informacion=> film), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>


<table>
    <thead>
       <tr>
       	<th>Residents: </th>
       </tr>
    </thead>
    <tbody>
		<%  @informacion["residentConnection"]["residents"].each do |residente| %>
       	<td> </td>
       	<td><%= link_to residente["name"], character_path(:content=> residente["id"] ), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>

app/views/starship/index.html.erb
<h1>STAR WAR STARSHIP</h1>


<table>
    <thead>
       <tr>
       	<th>Name: </th>
       	<th><%= @informacion["name"] %></th>
 		

       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Model: </th>
       	<th><%= @informacion["model"] %></th>
       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>
        <th>starshipClass: </th>
        <th><%= @informacion["starshipClass"] %></th>
       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>
       	<th>Manufacturer: </th>
       	<th><%= @informacion["manufacturers"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Cost in credits: </th>
       	<th><%= @informacion["costInCredits"] %></th>
       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
       	<th>Length: </th>
       	<th><%= @informacion["length"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
        <th>Crew: </th>
        <th><%= @informacion["crew"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
        <th>passengers: </th>
        <th><%= @informacion["passengers"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>max_atmosphering_speed: </th>
       	<th><%= @informacion["maxAtmospheringSpeed"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
        <th>Hyperdrive rating: </th>
        <th><%= @informacion["hyperdriveRating"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
        <th>Mglt: </th>
        <th><%= @informacion["MGLT"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Cargo capacity: </th>
       	<th><%= @informacion["cargoCapacity"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Consumables: </th>
       	<th><%= @informacion["consumables"] %></th>
       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
        <th>Films: </th>
       </tr>
    </thead>
    <tbody>
    <%  @informacion["filmConnection"]["films"].each do |film| %>
        <td> </td>
        <td><%= link_to film["title"], pelicula_path(:informacion=> film ), class: "btn btn-primary" %></td>
       </tr>
         <% end %>
    </tbody>
</table>


<table>
    <thead>
       <tr>
        <th>Pilots: </th>
       </tr>
    </thead>
    <tbody>
    <%  @informacion["pilotConnection"]["pilots"].each do |pilot| %>
        <td> </td>
        <td><%= link_to pilot["name"], character_path(:content=> pilot["id"] ), class: "btn btn-primary" %></td>
       </tr>
         <% end %>
    </tbody>
</table>

app/views/welcome/index.html.erb
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th> </th>
        <th> Año Lanzamiento </th>
        <th> </th>
        <th> Director </th>
        <th> </th>
        <th> Productor(es)</th>
        <th> </th>
        <th> Número de episodio </th>

        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
    <%   @response["data"]["allFilms"]["edges"].each do |persona| %>
        <td><%= link_to persona["node"]["title"], pelicula_path(:informacion=> persona["node"] ), class: "btn btn-primary" %></td>
        <td> | </td>
        <td><%= persona["node"]["releaseDate"] %></td>
        <td> | </td>
        <td><%= persona["node"]["director"] %></td>
        <td> | </td>
        <td><%= persona["node"]["producers"] %></td>
        <td> | </td>
        <td><%= persona["node"]["episodeID"] %></td>
       </tr>
         <% end %>
    </tbody>
  </table>

app/views/welcome/search.html.erb
<h1> Búsqueda </h1>


<%  @personas.each do |persona| %>
<%  if persona["name"].include? @parametros %>
       	<td><%= link_to persona["name"], character_path(:content=> persona ), class: "btn btn-primary" %></td>
		<% end %>
<% end %>

<%  @starships.each do |starship| %>
<%  if starship["name"].include? @parametros %>
       	<td><%= link_to starship["name"], starship_path(:content=> starship ), class: "btn btn-primary" %></td>
		<% end %>
<% end %>

<%  @films.each do |film| %>
<%  if film["title"].include? @parametros %>
       	<td><%= link_to film["title"], pelicula_path(:informacion=> film ), class: "btn btn-primary" %></td>
		<% end %>
<% end %>

<%  @planets.each do |planet| %>
<%  if planet["name"].include? @parametros %>
       	<td><%= link_to planet["name"], planet_path(:content=> planet, :hola=>"hola"), class: "btn btn-primary" %></td>
		<% end %>
<% end %>